Algoritmo "nota media"

Var

nome: caracter
nota1: real
nota2: real
nota3: real
total: real
media: real

Inicio

escreval("Digite seu nome:")
leia(nome)
escreval("escreva sua primeira nota:")
leia(nota1)
escreval("escreva sua segunda nota:")
leia(nota2)
escreval("escreva a sua terceira nota")
leia(nota3)
total<-nota1+nota2+nota3
escreval("total",nota1,nota2,nota3)
media<-total/3
escreval("media",media)


Fimalgoritmo