Algoritmo "NUMERO EXT"

Var
numero : inteiro

Inicio
escreval("escreva um numero de 1 a 10")
leia (numero)

escolha(numero)
caso 1
escreval("UM")

caso 2
escreval("DOIS")

caso 3
escreval("TRES")

caso 4
escreval("QUATRO")

caso 5
escreval("CINCO")

caso 6
escreval("SEIS")

caso 7
escreval("SETE")

caso 8
escreval("OITO")

caso 9
escreval("NOVE")

caso 10
escreval("DEZ")

outrocaso
escreval("numero nao reconhecido")

fimescolha

Fimalgoritmo