Algoritmo "Metro quadrado"

Var

comprimento: real
largura : real
metro_quadrado: real
preco_do_metro: real

Inicio

escreval("qual o comprimento do seu lote ?")
leia(comprimento)
escreval("qual a largura do seu lote ?")
leia(largura)
escreval("o preço do metro de contrução é de R$850,00")
metro_quadrado<-comprimento*largura
preco_do_metro<-850,00
escreval("o custo total da contrucao é de ", metro_quadrado * preco_do_metro)


Fimalgoritmo